# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Classificator
                                 A QGIS plugin
 classification of the types of permitted use of land plots in the cadastre based on a dictionary with the possibility of supplementing it
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-02
        copyright            : (C) 2021 by Anastasia Zavorotnyaya
        email                : anastasiaskbb@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Classificator class from file Classificator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Classificator import Classificator
    return Classificator(iface)
